// Header automatically generated by manifest_parser.
// Don't modify this file!

#ifndef OS_MANIFEST_HEADER
#define OS_MANIFEST_HEADER

extern OSCommand *_commands[];
extern size_t _commandCount;

extern OSCommand _osCommandCopy;
#define _OS_MENU_ITEM_TYPE_FOR_osCommandCopy OSMenuItem_COMMAND
#define osCommandCopy (&_osCommandCopy)
extern OSCommand _osCommandPaste;
#define _OS_MENU_ITEM_TYPE_FOR_osCommandPaste OSMenuItem_COMMAND
#define osCommandPaste (&_osCommandPaste)
extern OSCommand _osCommandCut;
#define _OS_MENU_ITEM_TYPE_FOR_osCommandCut OSMenuItem_COMMAND
#define osCommandCut (&_osCommandCut)
extern OSCommand _osCommandDelete;
#define _OS_MENU_ITEM_TYPE_FOR_osCommandDelete OSMenuItem_COMMAND
#define osCommandDelete (&_osCommandDelete)
extern OSCommand _osCommandUndo;
#define _OS_MENU_ITEM_TYPE_FOR_osCommandUndo OSMenuItem_COMMAND
#define osCommandUndo (&_osCommandUndo)
extern OSCommand _osCommandRedo;
#define _OS_MENU_ITEM_TYPE_FOR_osCommandRedo OSMenuItem_COMMAND
#define osCommandRedo (&_osCommandRedo)
extern OSCommand _osCommandRepeat;
#define _OS_MENU_ITEM_TYPE_FOR_osCommandRepeat OSMenuItem_COMMAND
#define osCommandRepeat (&_osCommandRepeat)
extern OSCommand _osCommandSelectAll;
#define _OS_MENU_ITEM_TYPE_FOR_osCommandSelectAll OSMenuItem_COMMAND
#define osCommandSelectAll (&_osCommandSelectAll)
extern OSMenuSpecification _osMenuTextboxContext;
#define _OS_MENU_ITEM_TYPE_FOR_osMenuTextboxContext OSMenuItem_SUBMENU
#define osMenuTextboxContext (&_osMenuTextboxContext)
extern OSCommand _osDialogStandardOK;
#define _OS_MENU_ITEM_TYPE_FOR_osDialogStandardOK OSMenuItem_COMMAND
#define osDialogStandardOK (&_osDialogStandardOK)
extern OSCommand _osDialogStandardCancel;
#define _OS_MENU_ITEM_TYPE_FOR_osDialogStandardCancel OSMenuItem_COMMAND
#define osDialogStandardCancel (&_osDialogStandardCancel)
extern OSWindowSpecification *osDialogStandard;
extern OSWindowSpecification *osDialogTextPrompt;

#ifdef OS_MANIFEST_DEFINITIONS

OSCommand _osCommandCopy = {
	.identifier = 0,
	.label = (char *) "Copy",
	.labelBytes = 6,
	.name = (char *) "",
	.nameBytes = 0,
	.shortcut = (char *) "Ctrl+C",
	.shortcutBytes = 6,
	.access = (char *) "",
	.accessBytes = 0,
	.radio = (char *) "",
	.radioBytes = 0,
	.checkable = false,
	.defaultCheck = false,
	.defaultDisabled = true,
	.radioCheck = false,
	.dangerous = false,
	.iconID = 0,
	.callback = { nullptr, nullptr },
};

OSCommand _osCommandPaste = {
	.identifier = 1,
	.label = (char *) "Paste",
	.labelBytes = 7,
	.name = (char *) "",
	.nameBytes = 0,
	.shortcut = (char *) "Ctrl+V",
	.shortcutBytes = 6,
	.access = (char *) "",
	.accessBytes = 0,
	.radio = (char *) "",
	.radioBytes = 0,
	.checkable = false,
	.defaultCheck = false,
	.defaultDisabled = true,
	.radioCheck = false,
	.dangerous = false,
	.iconID = 0,
	.callback = { nullptr, nullptr },
};

OSCommand _osCommandCut = {
	.identifier = 2,
	.label = (char *) "Cut",
	.labelBytes = 5,
	.name = (char *) "",
	.nameBytes = 0,
	.shortcut = (char *) "Ctrl+X",
	.shortcutBytes = 6,
	.access = (char *) "",
	.accessBytes = 0,
	.radio = (char *) "",
	.radioBytes = 0,
	.checkable = false,
	.defaultCheck = false,
	.defaultDisabled = true,
	.radioCheck = false,
	.dangerous = false,
	.iconID = 0,
	.callback = { nullptr, nullptr },
};

OSCommand _osCommandDelete = {
	.identifier = 3,
	.label = (char *) "Delete",
	.labelBytes = 8,
	.name = (char *) "",
	.nameBytes = 0,
	.shortcut = (char *) "Del",
	.shortcutBytes = 3,
	.access = (char *) "",
	.accessBytes = 0,
	.radio = (char *) "",
	.radioBytes = 0,
	.checkable = false,
	.defaultCheck = false,
	.defaultDisabled = true,
	.radioCheck = false,
	.dangerous = false,
	.iconID = 0,
	.callback = { nullptr, nullptr },
};

OSCommand _osCommandUndo = {
	.identifier = 4,
	.label = (char *) "Undo",
	.labelBytes = 6,
	.name = (char *) "",
	.nameBytes = 0,
	.shortcut = (char *) "Ctrl+Z",
	.shortcutBytes = 6,
	.access = (char *) "",
	.accessBytes = 0,
	.radio = (char *) "",
	.radioBytes = 0,
	.checkable = false,
	.defaultCheck = false,
	.defaultDisabled = true,
	.radioCheck = false,
	.dangerous = false,
	.iconID = 0,
	.callback = { nullptr, nullptr },
};

OSCommand _osCommandRedo = {
	.identifier = 5,
	.label = (char *) "Redo",
	.labelBytes = 6,
	.name = (char *) "",
	.nameBytes = 0,
	.shortcut = (char *) "Ctrl+Y",
	.shortcutBytes = 6,
	.access = (char *) "",
	.accessBytes = 0,
	.radio = (char *) "",
	.radioBytes = 0,
	.checkable = false,
	.defaultCheck = false,
	.defaultDisabled = true,
	.radioCheck = false,
	.dangerous = false,
	.iconID = 0,
	.callback = { nullptr, nullptr },
};

OSCommand _osCommandRepeat = {
	.identifier = 6,
	.label = (char *) "Repeat",
	.labelBytes = 8,
	.name = (char *) "",
	.nameBytes = 0,
	.shortcut = (char *) "Ctrl+Shift+Z",
	.shortcutBytes = 12,
	.access = (char *) "",
	.accessBytes = 0,
	.radio = (char *) "",
	.radioBytes = 0,
	.checkable = false,
	.defaultCheck = false,
	.defaultDisabled = true,
	.radioCheck = false,
	.dangerous = false,
	.iconID = 0,
	.callback = { nullptr, nullptr },
};

OSCommand _osCommandSelectAll = {
	.identifier = 7,
	.label = (char *) "Select All",
	.labelBytes = 12,
	.name = (char *) "",
	.nameBytes = 0,
	.shortcut = (char *) "Ctrl+A",
	.shortcutBytes = 6,
	.access = (char *) "",
	.accessBytes = 0,
	.radio = (char *) "",
	.radioBytes = 0,
	.checkable = false,
	.defaultCheck = false,
	.defaultDisabled = true,
	.radioCheck = false,
	.dangerous = false,
	.iconID = 0,
	.callback = { nullptr, nullptr },
};

OSMenuItem __osMenuTextboxContext[] = {
	{ _OS_MENU_ITEM_TYPE_FOR_osCommandCut, &_osCommandCut },
	{ _OS_MENU_ITEM_TYPE_FOR_osCommandCopy, &_osCommandCopy },
	{ _OS_MENU_ITEM_TYPE_FOR_osCommandPaste, &_osCommandPaste },
	{ OSMenuItem_SEPARATOR, nullptr },
	{ _OS_MENU_ITEM_TYPE_FOR_osCommandDelete, &_osCommandDelete },
	{ OSMenuItem_SEPARATOR, nullptr },
	{ _OS_MENU_ITEM_TYPE_FOR_osCommandSelectAll, &_osCommandSelectAll },
};

OSMenuSpecification _osMenuTextboxContext = {
	.name = (char *) "Textbox context menu",
	.nameBytes = 20,
	.minimumWidth = 0,
	.minimumHeight = 0,
	.items = __osMenuTextboxContext,
	.itemCount = 7,
};
OSCommand _osDialogStandardOK = {
	.identifier = 8,
	.label = (char *) "OK",
	.labelBytes = 4,
	.name = (char *) "",
	.nameBytes = 0,
	.shortcut = (char *) "",
	.shortcutBytes = 0,
	.access = (char *) "",
	.accessBytes = 0,
	.radio = (char *) "",
	.radioBytes = 0,
	.checkable = false,
	.defaultCheck = false,
	.defaultDisabled = false,
	.radioCheck = false,
	.dangerous = false,
	.iconID = 0,
	.callback = { nullptr, nullptr },
};

OSCommand _osDialogStandardCancel = {
	.identifier = 9,
	.label = (char *) "Cancel",
	.labelBytes = 8,
	.name = (char *) "",
	.nameBytes = 0,
	.shortcut = (char *) "",
	.shortcutBytes = 0,
	.access = (char *) "",
	.accessBytes = 0,
	.radio = (char *) "",
	.radioBytes = 0,
	.checkable = false,
	.defaultCheck = false,
	.defaultDisabled = false,
	.radioCheck = false,
	.dangerous = false,
	.iconID = 0,
	.callback = { nullptr, nullptr },
};

OSWindowSpecification _osDialogStandard = {
	.width = 400,
	.height = 110,
	.minimumWidth = 200,
	.minimumHeight = 160,
	.flags = 20,
	.title = (char *) "Message",
	.titleBytes = 7,
	.menubar = nullptr,
};

OSWindowSpecification *osDialogStandard = &_osDialogStandard;

OSWindowSpecification _osDialogTextPrompt = {
	.width = 320,
	.height = 120,
	.minimumWidth = 200,
	.minimumHeight = 160,
	.flags = 20,
	.title = (char *) "Message",
	.titleBytes = 7,
	.menubar = nullptr,
};

OSWindowSpecification *osDialogTextPrompt = &_osDialogTextPrompt;

OSCommand *_commands[] = {
	&_osCommandCopy,
	&_osCommandPaste,
	&_osCommandCut,
	&_osCommandDelete,
	&_osCommandUndo,
	&_osCommandRedo,
	&_osCommandRepeat,
	&_osCommandSelectAll,
	&_osDialogStandardOK,
	&_osDialogStandardCancel,
};

size_t _commandCount = 10;

#endif

#endif
