x86_64-elf-gcc -c dsargs.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dscontrol.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dsdebug.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dsfield.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dsinit.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dsmethod.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dsmthdat.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dsobject.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dsopcode.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dspkginit.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dsutils.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dswexec.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dswload.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dswload2.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dswscope.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c dswstate.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evevent.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evglock.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evgpe.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evgpeblk.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evgpeinit.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evgpeutil.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evhandler.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evmisc.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evregion.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evrgnini.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evsci.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evxface.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evxfevnt.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evxfgpe.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c evxfregn.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exconcat.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exconfig.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exconvrt.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c excreate.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exdebug.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exdump.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exfield.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exfldio.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exmisc.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exmutex.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exnames.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exoparg1.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exoparg2.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exoparg3.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exoparg6.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exprep.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exregion.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exresnte.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exresolv.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exresop.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exstore.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exstoren.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exstorob.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exsystem.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c extrace.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c exutils.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c hwacpi.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c hwesleep.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c hwgpe.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c hwpci.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c hwregs.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c hwsleep.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c hwtimer.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c hwvalid.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c hwxface.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c hwxfsleep.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsaccess.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsalloc.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsarguments.c -I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsconvert.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsdump.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsdumpdv.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nseval.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsinit.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsload.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsnames.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsobject.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsparse.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nspredef.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsprepkg.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsrepair.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsrepair2.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nssearch.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsutils.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nswalk.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsxfeval.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsxfname.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c nsxfobj.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c psargs.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c psloop.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c psobject.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c psopcode.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c psopinfo.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c psparse.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c psscope.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c pstree.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c psutils.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c pswalk.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c psxface.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rsaddr.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rscalc.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rscreate.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rsdump.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rsdumpinfo.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rsinfo.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rsio.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rsirq.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rslist.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rsmemory.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rsmisc.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rsserial.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rsutils.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c rsxface.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c tbdata.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c tbfadt.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c tbfind.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c tbinstal.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c tbprint.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c tbutils.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c tbxface.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c tbxfload.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c tbxfroot.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utaddress.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utalloc.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utascii.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utbuffer.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utcache.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utclib.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utcopy.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utdebug.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utdecode.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utdelete.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c uterror.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c uteval.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utexcep.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utglobal.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c uthex.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utids.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utinit.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utlock.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utmath.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utmisc.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utmutex.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utnonansi.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utobject.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utosi.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utownerid.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utpredef.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utprint.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utresdecode.c -I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utresrc.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utstate.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utstring.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utstrsuppt.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utstrtoul64.c -I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c uttrack.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utuuid.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utxface.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utxferror.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utxfinit.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone
x86_64-elf-gcc -c utxfmutex.c 	-I. -O0 -D_ACPICA_ESSENCE -D_GNU_SOURCE -std=c99 -Wall -Wextra -ffreestanding -mcmodel=large -g -Wno-unused-parameter -mno-red-zone

x86_64-elf-ar -rcs libacpica.a dsargs.o dscontrol.o dsdebug.o dsfield.o dsinit.o dsmethod.o dsmthdat.o dsobject.o dsopcode.o dspkginit.o dsutils.o dswexec.o dswload.o dswload2.o dswscope.o dswstate.o evevent.o evglock.o evgpe.o evgpeblk.o evgpeinit.o evgpeutil.o evhandler.o evmisc.o evregion.o evrgnini.o evsci.o evxface.o evxfevnt.o evxfgpe.o evxfregn.o exconcat.o exconfig.o exconvrt.o excreate.o exdebug.o exdump.o exfield.o exfldio.o exmisc.o exmutex.o exnames.o exoparg1.o exoparg2.o exoparg3.o exoparg6.o exprep.o exregion.o exresnte.o exresolv.o exresop.o exstore.o exstoren.o exstorob.o exsystem.o extrace.o exutils.o hwacpi.o hwesleep.o hwgpe.o hwpci.o hwregs.o hwsleep.o hwtimer.o hwvalid.o hwxface.o hwxfsleep.o nsaccess.o nsalloc.o nsarguments.o nsconvert.o nsdump.o nsdumpdv.o nseval.o nsinit.o nsload.o nsnames.o nsobject.o nsparse.o nspredef.o nsprepkg.o nsrepair.o nsrepair2.o nssearch.o nsutils.o nswalk.o nsxfeval.o nsxfname.o nsxfobj.o psargs.o psloop.o psobject.o psopcode.o psopinfo.o psparse.o psscope.o pstree.o psutils.o pswalk.o psxface.o rsaddr.o rscalc.o rscreate.o rsdump.o rsdumpinfo.o rsinfo.o rsio.o rsirq.o rslist.o rsmemory.o rsmisc.o rsserial.o rsutils.o rsxface.o tbdata.o tbfadt.o tbfind.o tbinstal.o tbprint.o tbutils.o tbxface.o tbxfload.o tbxfroot.o utaddress.o utalloc.o utascii.o utbuffer.o utcache.o utclib.o utcopy.o utdebug.o utdecode.o utdelete.o uterror.o uteval.o utexcep.o utglobal.o uthex.o utids.o utinit.o utlock.o utmath.o utmisc.o utmutex.o utnonansi.o utobject.o utosi.o utownerid.o utpredef.o utprint.o utresdecode.o utresrc.o utstate.o utstring.o utstrsuppt.o utstrtoul64.o uttrack.o utuuid.o utxface.o utxferror.o utxfinit.o utxfmutex.o
